# Generated by Django 5.0.3 on 2024-08-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='allergies_and_observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary')], null=True),
        ),
        migrations.AddField(
            model_name='pacient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='pacient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
