# Generated by Django 5.0.3 on 2024-03-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='adress',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='city',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
