# Generated by Django 5.0.3 on 2024-08-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacients', '0002_pacient_allergies_and_observations_pacient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
