# Generated by Django 5.1 on 2024-09-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacients', '0004_remove_pacient_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
