# Generated by Django 5.1 on 2024-09-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacients', '0005_alter_pacient_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
