# Generated by Django 5.0.3 on 2024-03-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('crm', models.CharField(max_length=13)),
                ('email', models.CharField(unique=True)),
                ('password', models.CharField()),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField()),
                ('city', models.CharField()),
                ('state', models.CharField(max_length=2)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
