# Generated by Django 5.0.3 on 2024-04-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_options_alter_doctor_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterModelManagers(
            name='doctor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user_permissions',
        ),
    ]
