# Generated by Django 5.0.3 on 2024-09-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_remove_doctor_address_remove_doctor_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='Dermatologist', max_length=100),
            preserve_default=False,
        ),
    ]
