# Generated by Django 5.1 on 2024-09-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='crm',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
